# config.make generated by configure script
POCO_CONFIG = iPhone-clang-libc++
POCO_BASE = /Users/xujianchao/Desktop/poco-1.7.8-all
POCO_BUILD = /Users/xujianchao/Desktop/poco-1.7.8-all
POCO_FLAGS = 
POCO_PREFIX = /Users/xujianchao/Desktop/poco-1.7.8-all/lib/iPhoneOS/arm64
OMIT = Data/MySQL Data/ODBC
POCO_ADD_INCLUDE = /Users/xujianchao/Desktop/poco-1.7.8-all/openssl/include/openssl
LINKMODE = STATIC
export POCO_CONFIG
export POCO_BASE
export POCO_BUILD
export POCO_FLAGS
export POCO_PREFIX
export POCO_ADD_INCLUDE
export LINKMODE
